### ISSUE TITLE
사전과제

### ISSUE THREAD

**Issue by jamonggg2** [jamonggg2/wanted-pre-onboarding-3-FE-quest#1]
## todo
- [ ] NextJS 등의 SSR 어플리케이션이 아닌, CSR 어플리케이션을 구축한다.
- [ ] 최소 3개 이상의 페이지를 가지도록 구현한다.
- [ ] 모든 페이지에 공통으로 반복되는 헤더와 사이드바가 있도록 구성한다.
